// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAujaP9J8pwQHe0_cWyNSUoP_g36xIrzkM',
    appId: '1:740366839070:web:300e89a770b0a9f7c46d0f',
    messagingSenderId: '740366839070',
    projectId: 'ecommerceapp-19634',
    authDomain: 'ecommerceapp-19634.firebaseapp.com',
    storageBucket: 'ecommerceapp-19634.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr3aS9pZKhppS4yz8GqPr2Xr-t5RYDVXc',
    appId: '1:740366839070:android:2486f6a4499e86bdc46d0f',
    messagingSenderId: '740366839070',
    projectId: 'ecommerceapp-19634',
    storageBucket: 'ecommerceapp-19634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwH9fQn5vriqTWRKhAr5INuP1hIdOaOGI',
    appId: '1:740366839070:ios:49b6a83c634957abc46d0f',
    messagingSenderId: '740366839070',
    projectId: 'ecommerceapp-19634',
    storageBucket: 'ecommerceapp-19634.appspot.com',
    androidClientId: '740366839070-pdvqpfii1tmaop3tkkaj04gmf440eo07.apps.googleusercontent.com',
    iosClientId: '740366839070-qq8k63lbd0nc73ai7ks5kr0esivpdb9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );

}